### ISSUE TITLE
Tracking issues in other packages that came up here

### ISSUE THREAD

**Issue by asinghvi17** [geocompx/geocompjl#9]
## Rasters.jl
- [ ] https://github.com/rafaqz/Rasters.jl/issues/755
- [x] https://github.com/rafaqz/Rasters.jl/issues/744 (will be solved by https://github.com/rafaqz/Rasters.jl/pull/745)
- [x] https://github.com/rafaqz/Rasters.jl/issues/749
## DimensionalData.jl
- [x] https://github.com/rafaqz/DimensionalData.jl/issues/803
- [x] https://github.com/rafaqz/DimensionalData.jl/issues/805
## GeometryOps.jl
- [ ] https://github.com/JuliaGeo/GeometryOps.jl/issues/210
- [ ] https://github.com/JuliaGeo/GeometryOps.jl/issues/212
- [ ] https://github.com/JuliaGeo/GeometryOps.jl/issues/215
- [x] https://github.com/JuliaGeo/GeometryOps.jl/pull/211
## GeoInterface.jl
- [ ] https://github.com/JuliaGeo/GeoInterface.jl/pull/156
- [x] https://github.com/JuliaGeo/GeoInterface.jl/pull/161
## GeoDataFrames.jl
- [x] https://github.com/evetion/GeoDataFrames.jl/pull/75
- [x] https://github.com/evetion/GeoDataFrames.jl/issues/119
- [x] https://github.com/evetion/GeoDataFrames.jl/issues/120
- [x] https://github.com/evetion/GeoDataFrames.jl/issues/121
## QuartoNotebookRunner.jl
- [ ] https://github.com/PumasAI/QuartoNotebookRunner.jl/pull/184
